### ISSUE TITLE
Volumio is unresponsive 

### ISSUE THREAD

**Issue by manmax1** [patrickkfkan/volumio-youtube2#11] opened 2023-06-28 17:10 UTC
Even after update to 1.1.2 beta my volumio is unresponsive .

How can I help ?

**Comment by lantama70** [comment] 2023-06-29 14:57
Same issue here. It corrupted my installation. Had to install newly. Installed the Plugin again. Next corruption.... Ypoutube2 and Youtube Music show the same issues

**Comment by patrickkfkan** [comment] 2023-06-29 15:09
ssh into Volumio, type :
```
cat /data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/package.json
```

What are the results?

**Comment by lantama70** [comment] 2023-07-03 15:53
Your recent update fixed the issue. Many thanks !

**Comment by Tea-pot** [comment] 2023-08-02 16:32
I assume this is related, in my case I was starting from scratch - fresh img on 32GB SDHC - volumio 3 ( updated before install )

this is what was happened:
`volumio@volumio:~/youtube2$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Downloading plugin at http://127.0.0.1:3000/plugin-serve/youtube2.zip
Progress: 30
Status :Creating install location
Downloading plugin at http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>Creating install location
Progress: 40
Status :Unpacking plugin
Downloading plugin at http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>Creating install location<br>Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Downloading plugin at http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin
Progress: 60
Status :Copying plugin to location
Downloading plugin at http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin<br>Copying plugin to location
Progress: 70
Status :Installing necessary utilities
Downloading plugin at http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin<br>Copying plugin to location<br>Installing necessary utilities
Progress: 70
Status :Installing necessary utilities
Downloading plugin at http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin<br>Copying plugin to location<br>Installing necessary utilities<br>YouTube2 plugin installed
Progress: 90
Status :Finalizing installation
Downloading plugin at http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin<br>Copying plugin to location<br>Installing necessary utilities<br>YouTube2 plugin installed<br>Finalizing installation
Progress: 100
Status :YouTube2 Successfully Installed, Do you want to enable the plugin now?
Downloading plugin at http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/youtube2.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin<br>Copying plugin to location<br>Installing necessary utilities<br>YouTube2 plugin installed<br>Finalizing installation<br>Finalizing installation
^C
volumio@volumio:~/youtube2$ volumio plugin update

This command will update the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 20
Status :Plugin stopped
Progress: 30
Status :Creating install location
Progress: 40
Status :Unpacking plugin
Progress: 60
Status :Updating plugin files
Progress: 70
Status :Installing necessary utilities
Progress: 70
Status :Installing necessary utilities
Progress: 90
Status :Finalizing installation
Progress: 100
Status :Successfully updated plugin
`

![yt2issue](https://github.com/patrickkfkan/volumio-youtube2/assets/35202371/bcfb1553-1cd0-4d0f-b774-d822651da67a)

Plugin does not work, I was able to use it on my old build.
I spent already couple of days trying to fix it, unfortunately all my efforts ends the same way, as shown above.

any thoughts?
Thank you in advance.
Node v18.17.0
npm 9.8.1

**Comment by patrickkfkan** [comment] 2023-08-02 18:00
This is a separate issue. 

What do the logs show when you enable the plugin?
```
$ journalctl -f -u volumio
```

Also, why are you using Node v18? Volumio 3 runs on Node v14, so the plugin might not be compatible with higher Node versions. But in any case, the logs should show the cause of failure.

**Comment by Tea-pot** [comment] 2023-08-02 19:32
thank you @patrickkfkan please find this log:

> volumio@volumio:~/volumio-youtube2$ journalctl -f -u volumio
> -- Logs begin at Thu 2019-02-14 10:11:59 UTC. --
> Aug 02 19:14:14 volumio sudo[1497]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Aug 02 19:14:14 volumio sudo[1497]: pam_unix(sudo:session): session closed for user root
> Aug 02 19:14:14 volumio volumio[915]: info: YouTube2 plugin installed
> Aug 02 19:14:14 volumio volumio[915]: Plugin install end detected on script
> Aug 02 19:14:14 volumio volumio[915]: info: Install script completed
> Aug 02 19:14:14 volumio volumio[915]: info: Adding reference to registry
> Aug 02 19:14:14 volumio volumio[915]: info: Done installing plugin.
> Aug 02 19:14:14 volumio volumio[915]: info: Folder /tmp/plugins removed
> Aug 02 19:14:14 volumio volumio[915]: info: Folder /tmp/downloaded_plugin.zip removed
> Aug 02 19:14:14 volumio volumio[915]: info: Folder /data/temp removed
> Aug 02 19:25:04 volumio volumio[915]: info: Enabling plugin youtube2
> Aug 02 19:25:04 volumio volumio[915]: info: Loading plugin "youtube2"...
> Aug 02 19:25:04 volumio volumio[915]: error: !!!! WARNING !!!!
> Aug 02 19:25:04 volumio volumio[915]: error: The plugin music_service/youtube2 failed to load, setting it to stopped. Error: SyntaxError: Unexpected token .
> Aug 02 19:25:04 volumio volumio[915]: error: Stack trace: /data/plugins/music_service/youtube2/dist/index.js:349
> Aug 02 19:25:04 volumio volumio[915]:                 const view = ViewHelper_1.default.getViewsFromUri(data.uri)?.[1];
> Aug 02 19:25:04 volumio volumio[915]:                                                                             ^
> Aug 02 19:25:04 volumio volumio[915]: SyntaxError: Unexpected token .
> Aug 02 19:25:04 volumio volumio[915]:     at createScript (vm.js:80:10)
> Aug 02 19:25:04 volumio volumio[915]:     at Object.runInThisContext (vm.js:139:10)
> Aug 02 19:25:04 volumio volumio[915]:     at Module._compile (module.js:617:28)
> Aug 02 19:25:04 volumio volumio[915]:     at Object.Module._extensions..js (module.js:664:10)
> Aug 02 19:25:04 volumio volumio[915]:     at Module.load (module.js:566:32)
> Aug 02 19:25:04 volumio volumio[915]:     at tryModuleLoad (module.js:506:12)
> Aug 02 19:25:04 volumio volumio[915]:     at Function.Module._load (module.js:498:3)
> Aug 02 19:25:04 volumio volumio[915]:     at Module.require (module.js:597:17)
> Aug 02 19:25:04 volumio volumio[915]:     at require (internal/module.js:11:18)
> Aug 02 19:25:04 volumio volumio[915]:     at PluginManager.loadCorePlugin (/volumio/app/pluginmanager.js:146:29)
> Aug 02 19:25:04 volumio volumio[915]:     at Promise._successFn (/volumio/app/pluginmanager.js:1565:19)
> Aug 02 19:25:04 volumio volumio[915]:     at nextTickCallback (/volumio/node_modules/kew/kew.js:47:28)
> Aug 02 19:25:04 volumio volumio[915]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
> Aug 02 19:25:04 volumio volumio[915]:     at process._tickCallback (internal/process/next_tick.js:181:9)
> Aug 02 19:25:04 volumio volumio[915]: error: !!!! WARNING !!!!
> Aug 02 19:25:04 volumio volumio[915]: info: Done.

You're right I probably shouldn't mess up with Node version, but just as a habit I have updated to latest, originally it my volumio build show node 8 in /usr/bin/node and volumio upon plugin installation yelled there is no node in /usr/local/bin so I started from fixing this to be able to proceed with installation.

**Comment by Tea-pot** [comment] 2023-08-02 20:14
@patrickkfkan just to let you know - all works, I should have started from scratch at very first sight of weird issue. Plugin works perfectly - no issue with installation, no issue with performance - I just have downloaded fresh img latest build - Volumio-3.512-2023-06-25-pi and everything runs perfectly. Thank you for your time.

deleted previous logs - non essential.

**Comment by patrickkfkan** [comment] 2023-08-02 20:25
Good to know ~  I'll close this issue for now.

**Closed as completed by patrickkfkan** 2023-08-02 20:25 UTC
